#!/usr/bin/env bash
# Marveen container entrypoint.
#
# Replicates the *non-interactive, per-deployment* slice of install-linux.sh:
# materializes .env / CLAUDE.md / SOUL.md / channel access.json from env vars,
# seeds ~/.claude (onboarding + skip-dangerous), idempotently scaffolds seed
# skills/scheduled-tasks/config, best-effort installs the channel plugin, then
# hands off to supervisord (dashboard + channels). It deliberately does NOT do
# the host-mutating installer steps (apt, swap, systemd, sudo, interactive Q&A).
set -euo pipefail

APP_DIR=/app
HOME_DIR="${HOME:-/home/marveen}"
log() { echo "[entrypoint] $*"; }

# ─────────────────────────────────────────────
# Config (env vars = source of truth, with defaults)
# ─────────────────────────────────────────────
OWNER_NAME="${OWNER_NAME:-Owner}"
BOT_NAME="${BOT_NAME:-Marveen}"
CHANNEL_PROVIDER="${CHANNEL_PROVIDER:-telegram}"
ALLOWED_CHAT_ID="${ALLOWED_CHAT_ID:-0}"
WEB_HOST="${WEB_HOST:-0.0.0.0}"
WEB_PORT="${WEB_PORT:-3420}"
MARVEEN_ENV="${MARVEEN_ENV:-linux-server}"

# Derive the ASCII slug the backend uses for tmux sessions / DB id / routing,
# matching install-linux.sh (NFKD -> ASCII -> lowercase dashes).
if [ -z "${MAIN_AGENT_ID:-}" ]; then
  MAIN_AGENT_ID="$(python3 - "$BOT_NAME" <<'PY'
import sys, unicodedata, re
s = unicodedata.normalize('NFKD', sys.argv[1].strip()).encode('ascii', 'ignore').decode()
s = re.sub(r'[^a-zA-Z0-9]+', '-', s).strip('-').lower()
print(s or 'marveen')
PY
)"
fi

# Recover a previously paired Telegram chat id from the persisted volume so the
# bot keeps replying after a container recreate, even if ALLOWED_CHAT_ID wasn't
# pinned in the env file.
if [ "$CHANNEL_PROVIDER" = "telegram" ] && { [ -z "$ALLOWED_CHAT_ID" ] || [ "$ALLOWED_CHAT_ID" = "0" ]; }; then
  acc="$HOME_DIR/.claude/channels/telegram/access.json"
  if [ -f "$acc" ]; then
    recovered="$(python3 -c "import json,sys
try:
    d=json.load(open(sys.argv[1])); a=d.get('allowFrom',[]); print(a[0] if a else '')
except Exception: print('')" "$acc" 2>/dev/null || true)"
    if [ -n "$recovered" ]; then
      ALLOWED_CHAT_ID="$recovered"
      log "recovered paired chat id from persisted access.json"
    fi
  fi
fi

# ─────────────────────────────────────────────
# .env  (chmod 600) — channels.sh & config.ts read this
# ─────────────────────────────────────────────
umask 077
{
  echo "# Generated by docker/entrypoint.sh — env vars are the source of truth."
  echo "CHANNEL_PROVIDER=${CHANNEL_PROVIDER}"
  echo "OWNER_NAME=${OWNER_NAME}"
  echo "BOT_NAME=${BOT_NAME}"
  echo "MAIN_AGENT_ID=${MAIN_AGENT_ID}"
  echo "WEB_HOST=${WEB_HOST}"
  echo "WEB_PORT=${WEB_PORT}"
  echo "MARVEEN_ENV=${MARVEEN_ENV}"
  [ -n "${OLLAMA_URL:-}" ]            && echo "OLLAMA_URL=${OLLAMA_URL}"
  [ -n "${DASHBOARD_TOKEN:-}" ]       && echo "DASHBOARD_TOKEN=${DASHBOARD_TOKEN}"
  [ -n "${DASHBOARD_PUBLIC_URL:-}" ]  && echo "DASHBOARD_PUBLIC_URL=${DASHBOARD_PUBLIC_URL}"
  [ -n "${HEARTBEAT_CALENDAR_ID:-}" ] && echo "HEARTBEAT_CALENDAR_ID=${HEARTBEAT_CALENDAR_ID}"
  [ -n "${GOOGLE_API_KEY:-}" ]        && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}"
  if [ "$CHANNEL_PROVIDER" = "telegram" ]; then
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}"
    echo "ALLOWED_CHAT_ID=${ALLOWED_CHAT_ID}"
  else
    echo "SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-}"
    echo "SLACK_APP_TOKEN=${SLACK_APP_TOKEN:-}"
    [ -n "${SLACK_CHANNEL_ID:-}" ] && echo "SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID}"
  fi
  # Claude auth so the tmux-spawned `claude` can authenticate. OAuth token wins
  # over API key; never emit both (Claude Code rejects that combo).
  if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    echo "CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}"
  elif [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}"
  fi
} > "$APP_DIR/.env"
chmod 600 "$APP_DIR/.env"
log ".env written (agent=${MAIN_AGENT_ID} provider=${CHANNEL_PROVIDER})"

if [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  log "WARNING: no CLAUDE_CODE_OAUTH_TOKEN or ANTHROPIC_API_KEY set — agents cannot run until you provide one (see DOCKER.md)."
fi

# ─────────────────────────────────────────────
# CLAUDE.md (regenerated each boot) + SOUL.md (only if absent)
# ─────────────────────────────────────────────
if [ -f "$APP_DIR/templates/CLAUDE.md.template" ]; then
  sed -e "s/{{OWNER_NAME}}/${OWNER_NAME}/g" \
      -e "s|{{INSTALL_DIR}}|${APP_DIR}|g" \
      -e "s/{{CHAT_ID}}/${ALLOWED_CHAT_ID}/g" \
      -e "s/{{BOT_NAME}}/${BOT_NAME}/g" \
      -e "s/{{MAIN_AGENT_ID}}/${MAIN_AGENT_ID}/g" \
      "$APP_DIR/templates/CLAUDE.md.template" > "$APP_DIR/CLAUDE.md"
fi
if [ -f "$APP_DIR/templates/SOUL.md.template" ] && [ ! -f "$APP_DIR/SOUL.md" ]; then
  sed -e "s/{{OWNER_NAME}}/${OWNER_NAME}/g" \
      -e "s/{{BOT_NAME}}/${BOT_NAME}/g" \
      "$APP_DIR/templates/SOUL.md.template" > "$APP_DIR/SOUL.md"
fi

# ─────────────────────────────────────────────
# ~/.claude tree + first-run seeds (so the headless tmux TUI never parks
# on the onboarding / bypass-permissions dialogs)
# ─────────────────────────────────────────────
mkdir -p "$HOME_DIR/.claude/channels" "$HOME_DIR/.claude/skills" \
         "$HOME_DIR/.claude/scheduled-tasks" "$HOME_DIR/.claude/tools"
chmod 700 "$HOME_DIR/.claude" 2>/dev/null || true

python3 - "$HOME_DIR" <<'PY'
import json, os, pathlib, sys
home = sys.argv[1]

p = pathlib.Path(home, ".claude.json")
data = {}
if p.exists():
    try: data = json.loads(p.read_text())
    except Exception: data = {}
data["hasCompletedOnboarding"] = True
data.setdefault("theme", "dark")
p.write_text(json.dumps(data, indent=2))
try: os.chmod(p, 0o600)
except Exception: pass

s = pathlib.Path(home, ".claude", "settings.json")
sd = {}
if s.exists():
    try: sd = json.loads(s.read_text())
    except Exception: sd = {}
sd["skipDangerousModePermissionPrompt"] = True
s.parent.mkdir(parents=True, exist_ok=True)
s.write_text(json.dumps(sd, indent=2))
try: os.chmod(s, 0o600)
except Exception: pass
PY

# ─────────────────────────────────────────────
# Channel state dir: token + access.json (access.json kept if it already
# exists, so a completed pairing on the volume survives restarts)
# ─────────────────────────────────────────────
CHANNEL_DIR="$HOME_DIR/.claude/channels/$CHANNEL_PROVIDER"
mkdir -p "$CHANNEL_DIR"
if [ "$CHANNEL_PROVIDER" = "telegram" ] && [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
  (umask 077; printf 'TELEGRAM_BOT_TOKEN=%s\n' "${TELEGRAM_BOT_TOKEN}" > "$CHANNEL_DIR/.env")
  if [ ! -f "$CHANNEL_DIR/access.json" ]; then
    printf '%s\n' '{ "dmPolicy": "pairing", "allowFrom": [], "groups": {}, "pending": {} }' > "$CHANNEL_DIR/access.json"
  fi
elif [ "$CHANNEL_PROVIDER" = "slack" ] && [ -n "${SLACK_BOT_TOKEN:-}" ]; then
  (umask 077; printf 'SLACK_BOT_TOKEN=%s\nSLACK_APP_TOKEN=%s\n' "${SLACK_BOT_TOKEN}" "${SLACK_APP_TOKEN:-}" > "$CHANNEL_DIR/.env")
  if [ ! -f "$CHANNEL_DIR/access.json" ]; then
    printf '%s\n' '{ "dmPolicy": "pairing", "allowFrom": [], "channels": {}, "pending": {} }' > "$CHANNEL_DIR/access.json"
  fi
fi

# ─────────────────────────────────────────────
# Idempotent seeding (never overwrite existing user customizations)
# ─────────────────────────────────────────────
mkdir -p "$APP_DIR/store" "$APP_DIR/agents"

# skill-factory (self-learning meta-skill)
if [ -d "$APP_DIR/skills/skill-factory" ] && [ ! -e "$HOME_DIR/.claude/skills/skill-factory/SKILL.md" ]; then
  mkdir -p "$HOME_DIR/.claude/skills/skill-factory"
  cp -r "$APP_DIR/skills/skill-factory/." "$HOME_DIR/.claude/skills/skill-factory/" 2>/dev/null || true
fi

# fleet-level seed skills
if [ -d "$APP_DIR/seed-skills" ]; then
  for d in "$APP_DIR/seed-skills"/*/; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    [ -e "$HOME_DIR/.claude/skills/$name" ] && continue
    cp -r "$d" "$HOME_DIR/.claude/skills/$name"
  done
fi

# scheduled tasks (templates/ + seed-) with placeholder substitution
seed_scheduled() {
  local srcroot="$1"
  [ -d "$srcroot" ] || return 0
  for d in "$srcroot"/*/; do
    [ -d "$d" ] || continue
    local name; name="$(basename "$d")"
    [ "$name" = "bumblebee-hygiene-scan" ] && continue
    local target="$HOME_DIR/.claude/scheduled-tasks/$name"
    [ -d "$target" ] && continue
    mkdir -p "$target"
    for f in "$d"*; do
      [ -f "$f" ] || continue
      sed -e "s/{{MAIN_AGENT_ID}}/${MAIN_AGENT_ID}/g" \
          -e "s/{{BOT_NAME}}/${BOT_NAME}/g" \
          -e "s/{{OWNER_NAME}}/${OWNER_NAME}/g" \
          -e "s|{{INSTALL_DIR}}|${APP_DIR}|g" \
          "$f" > "$target/$(basename "$f")"
    done
  done
}
seed_scheduled "$APP_DIR/templates/scheduled-tasks"
seed_scheduled "$APP_DIR/seed-scheduled-tasks"

# default config -> store/
if [ -d "$APP_DIR/seed-config" ]; then
  for cfg in "$APP_DIR/seed-config"/*.json; do
    [ -f "$cfg" ] || continue
    t="$APP_DIR/store/$(basename "$cfg")"
    [ -f "$t" ] || cp "$cfg" "$t"
  done
fi

# ─────────────────────────────────────────────
# Channel plugin install/enable (best-effort; needs network + valid auth)
# ─────────────────────────────────────────────
if command -v claude >/dev/null 2>&1 && { [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] || [ -n "${ANTHROPIC_API_KEY:-}" ]; }; then
  case "$CHANNEL_PROVIDER" in
    slack)   MK="Szotasz/marveen-marketplace";        PID="slack-channel@marveen-marketplace"; SHORT="slack-channel" ;;
    discord) MK="anthropics/claude-plugins-official"; PID="discord@claude-plugins-official";   SHORT="discord" ;;
    *)       MK="anthropics/claude-plugins-official"; PID="telegram@claude-plugins-official";  SHORT="telegram" ;;
  esac
  log "ensuring ${CHANNEL_PROVIDER} channel plugin is installed/enabled (best-effort)…"
  ( cd "$APP_DIR"
    claude plugin marketplace add "$MK" >/dev/null 2>&1 || true
    claude plugin install "$PID" >/dev/null 2>&1 || true
    claude plugin enable "${SHORT}@${MK##*/}" --scope project >/dev/null 2>&1 \
      || claude plugin enable "$PID" --scope project >/dev/null 2>&1 || true
  ) || true
fi

# ─────────────────────────────────────────────
# Hand off to the supervisor (dashboard + channels, auto-restart)
# ─────────────────────────────────────────────
log "starting supervisord (dashboard + channels) on ${WEB_HOST}:${WEB_PORT}"
exec supervisord -c "$APP_DIR/docker/supervisord.conf"
